### ISSUE TITLE
feature request: Publish as a docker image

### ISSUE THREAD

**Issue by jfisbein** [ynqa/jnv#19]
If published as a Docker image it can be used easily without depending on cargo or homebrew

**Comment by VaishnavVerma** [comment]
@jfisbein can you assign this to me ?

**Comment by jfisbein** [comment]
Sorry, only the project admin can assign the issue to you.
@ynqa

**Comment by VaishnavVerma** [comment]
@ynqa can you assign this to me ?

**Comment by ynqa** [comment]
@VaishnavVerma cc @jfisbein Sorry for the delayed response, I have added you as an assignee.

**Comment by ynqa** [comment]
@VaishnavVerma You might already be considering. I would appreciate it if you could make the image at runtime as small as possible using multi-stage builds. There might be other areas that can be optimized, but at this initial stage, this is my only request.

**Comment by grodin** [comment]
Since the person who offered to take this has turned into a ghost, is this up for grabs?

I took note of your comment about your wanting a minimal image.

**Comment by ynqa** [comment]
@grodin It seems they've turned into a ghost without me noticing 👻 As of now, there's no one working on it.
