### ISSUE TITLE
How about replacement `jq` with `jaq`?

### ISSUE THREAD

**Issue by ynqa** [ynqa/jnv#24]
At the time of v0.1.0, the author deemed it most appropriate to use the original jq.

However, managing C-related stuff during build time had to be undertaken, and this was underestimated at the release of v0.1.0. After actually releasing and taking a look the installation error issues that were raised, it became apparent that continuing to use jq might not be the best decision.

Then, there is a project in Rust called [jaq](https://github.com/01mf02/jaq), which is a jq-clone. I hope to discuss whether or not to replace jq with jaq, and whether it is feasible to do so.

Here's a rough outline of the pros and cons:

[jq](https://github.com/jqlang/jq) ([j9](https://github.com/ynqa/j9))
- pros
  - As an original implementation, all filters defined here are, of course, available for use
- cons
  - Requires management of C dependencies, which might pose issues during build phase
    - https://github.com/ynqa/jnv/issues/6
    - https://github.com/ynqa/jnv/issues/13
    - https://github.com/ynqa/jnv/issues/1

[jaq](https://github.com/01mf02/jaq)
- pros
  - pure Rust, there is no need to manage C dependencies
- cons
  - jq-clone, not all filters may be supported
     - e.g. https://github.com/01mf02/jaq/issues/112
     - My concern is with this point. Ideally, it would be better if all features were available for use (Or maybe it's sufficient if only the basic filters are available...?)

**Comment by dwvisser** [comment]
I say it’s okay to have *jaq*’s reduced set of available filters, if more people can build and use *jnv*. 😊

**Comment by moritzwilksch** [comment]
I agree with @dwvisser and would personally prefer an easy-to-build pure rust tool over packaging C deps. `ripgrep` took a similar approach where the rust `regex` crate they use lacks some features (eg look-ahead/behind is not supported) but in return doesn't depend on C.

**Comment by ardrigh** [comment]
I would like to start using this tool if it was pure Rust. Even if there weren't a complete match of filters.

jq was unmaintained entirely for a number of years. At least if you only have Rust dependencies it will be easier to manage if such a situation happens again.

**Comment by corneliusroemer** [comment]
Can you maybe try out how it works with jaq, allowing choice of jaq and jaq, then deprecate jq if jaq is good enough.

**Comment by pavelzw** [comment]
I'm also having some issues compiling j9-sys

https://github.com/conda-forge/staged-recipes/pull/25806#issuecomment-2041434460

```
checking host system type... 
  --- stderr
  configure.ac:11: installing 'config/ar-lib'
  configure.ac:8: installing 'config/compile'
  configure.ac:19: installing 'config/config.guess'
  configure.ac:19: installing 'config/config.sub'
  configure.ac:9: installing 'config/install-sh'
  configure.ac:9: installing 'config/missing'
  Makefile.am: installing 'config/depcomp'
  configure.ac: installing 'config/ylwrap'
  parallel-tests: installing 'config/test-driver'
  Invalid configuration `/home/conda/staged-recipes/build_artifacts/jnv_1712488275842/_build_env/bin/x86_64-conda-linux-gnu': more than four components
  configure: error: /bin/sh /home/conda/staged-recipes/build_artifacts/jnv_1712488275842/work/target/x86_64-unknown-linux-gnu/release/build/j9-sys-b50a7ed31c9b8fd9/out/jq_build/config/config.sub /home/conda/staged-recipes/build_artifacts/jnv_1712488275842/_build_env/bin/x86_64-conda-linux-gnu failed
  thread 'main' panicked at /home/conda/staged-recipes/build_artifacts/jnv_1712488275842/_build_env/.cargo/registry/src/index.crates.io-6f17d22bba15001f/autotools-0.2.6/src/lib.rs:781:5:
```

Switching to `jaq` would fix this 😅
