### ISSUE TITLE
Feature Request: Copy current JSON displayed

### ISSUE THREAD

**Issue by Explosion-Scratch** [ynqa/jnv#27]
This would be very useful, for example when entering `.[].timestamp` copy the JSON shown:

<img width="249" alt="image" src="https://github.com/ynqa/jnv/assets/61319150/d3362572-43b8-49b9-90dc-27aa310d9b0e">

**Comment by danymat** [comment]
Hey, more than that we could have 2 bindings:
- One for copying the highlighted one
- One for copying the whole output

**Comment by ynqa** [comment]
Related crates
- https://github.com/1Password/arboard
- https://github.com/aweinstock314/rust-clipboard

**Comment by kud** [comment]
I was close to creating a question or feature request, but here we are! Yeah, I definitely would like to see this feature as well. 😊

**Comment by kud** [comment]
Cooooooooooooool, thanks!
