### ISSUE TITLE
Native keyboard shortcuts for quickly navigating the query don't work

### ISSUE THREAD

**Issue by hu0p** [ynqa/jnv#8]
On macOS, I frequently use Option+Arrow Keys to jump through text inputs one "word" at a time. This works in the native shell as well as most text inputs. Would it be possible to support this in jnv's query input?

Thanks for making this! It's a neat tool that I've enjoyed with the minimal usage I've had so far, and I hope it's been a fun project to work on.

**Comment by ynqa** [comment]
@hu0p Thanks for your suggestions 📝 

I'm currently investigating the cause, but I've discovered that pressing Option+Arrow is evaluated as Esc by crossterm (my environment is MacOS using Iterm2).

On the other hand, the combination of Option+{b, f} is recognized correctly, so I'm planning to provide equivalent functionality with shortcuts for Option+{b, f}.

**Comment by hu0p** [comment]
I also use iTerm 2. I forgot that I changed something in my configuration to make this work the same way. Sorry about that! This sounds like a good approach to me.

**Comment by ynqa** [comment]
> the combination of Option+{b, f} 

@hu0p I implemented these shortcut at https://github.com/ynqa/jnv/pull/33. Please check it 👍
