### ISSUE TITLE
Feature Request: Support JSON stream

### ISSUE THREAD

**Issue by icholy** [ynqa/jnv#9]
It would be nice if jnv supported sequences of json objects separate by newlines the way jq does:

``` json
{ "a": 123 }
{ "a": 123 }
```

Note: [fx](https://github.com/antonmedv/fx) also supports this.

**Comment by mholt** [comment]
This would be really useful for inspecting Caddy logs.

**Comment by robpottify** [comment]
Ditto useful for our use cases. 

We're talking about JSON Lines, yes? https://jsonlines.org

**Comment by icholy** [comment]
@robpottify The objects are delimited by newlines, but `jq` allows a single object to span multiple lines:

``` json
{
  "a": 123
}
{
  "a": 321
}
```

**Comment by robpottify** [comment]
Ah ok, so subtly different as JSON Lines prescribes newlines between records.

Should I raise a separate gh issue ticket for JSON Lines, or are they similar enough to be prioritised as one feature?

**Comment by icholy** [comment]
@robpottify JSON lines is a subset of JSON streams.

**Comment by ynqa** [comment]
In #28, we've made it possible to handle multiple JSONs. Please check whether the problem addressed in this issue has been resolved.

**Comment by ynqa** [comment]
@icholy In #28, we've made it possible to handle multiple JSONs. Please check whether the problem addressed in this issue has been resolved.

**Comment by icholy** [comment]
@ynqa tested and working perfectly!

**Comment by ynqa** [comment]
@icholy v0.2.0, which addresses this issue, has been released. Please check it out 🎉
